name: Test

on: workflow_dispatch

jobs: 
  local-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: ls
        run: ls -al
        #run: ls -al
