name: Hola Mundo

#para ejecutar el workflow
on: [push]
#on: 
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

#ejecutar todo lo que se necesite en el servidor
jobs:

  hola:
    - name: Read file
      run: cat hola.txt

  other:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7  

      - name: LS
        run: ls -al

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4
        with:
          node-version: latest

      - name: node version
        run: node --version

      - name: PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      
      - name: node version
        run: php --version

            

