name: Hola Mundo

#para ejecutar el workflow
on: [push]

#ejecutar todo lo que se necesite en el servidor
jobs:
  hola:
    runs=on: ubuntu-latest

    steps:
    - name: Hola Mundo
      run: echo "Hola mundo"